[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "cython",
    "numpy",
    "scipy"
]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ['qmeq',
                'qmeq/approach',
                'qmeq/approach/base',
                'qmeq/approach/elph',
                'qmeq/builder',
                'qmeq/specfunc',
                'qmeq/tests',
                'qmeq/wrappers']

[tool.setuptools.package-data]
qmeq/approach=['*.pyx', '*.c', '*.pyd', '*.o', '*.so']
qmeq/approach/base=['*.pyx', '*.c', '*.pyd', '*.o', '*.so']
qmeq/approach/elph=['*.pyx', '*.c', '*.pyd', '*.o', '*.so']
qmeq/specfunc=['*.pyx', '*.c', '*.pyd', '*.o', '*.so']
qmeq/wrappers=['*.pyx', '*.c', '*.pyd', '*.o', '*.so']

[project]
name = "qmeq"
version = "1.2.0"
description = "Package for transport calculations in quantum dots using approximate quantum master equations"
authors = [{ name="Gediminas Kirsanskas", email="qmeq.package@gmail.com" }]
license = { text = "BSD 2-Clause" }

classifiers = ['Development Status :: 5 - Production/Stable',
               'Intended Audience :: Science/Research',
               'License :: OSI Approved :: BSD License',
               'Operating System :: MacOS',
               'Operating System :: Microsoft :: Windows',
               'Operating System :: POSIX',
               'Operating System :: Unix',
               'Programming Language :: Cython',
               'Programming Language :: Python :: 3',
               'Topic :: Scientific/Engineering :: Physics']

dependencies = [
    "numpy",
    "scipy",
    "cython"
]

[project.urls]
Homepage = 'http://github.com/gedaskir/qmeq'

[project.readme]
file="README.md"
content-type = "text/markdown"